services:
  postgres:
    image: postgres:14.9
    container_name: postgres
    restart: always
    shm_size: 256mb  # Improves performance, especially with dbt or parallel queries
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}  # Recommended for versioned structure
    command: >
      -c max_wal_size=2GB
      -c checkpoint_timeout=15min
      -c shared_buffers=128MB
      -c wal_compression=on
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pg_data:
